/// Generated by Flutter GetX Starter on 2023-11-05 07:21
import 'package:get/get.dart';
import 'package:ndialog/ndialog.dart';

import '../../../core/services/database.dart';
import 'location_collection_state.dart';

class location_collectionLogic extends GetxController {
  final state = location_collectionState();

  final DataBaseServices _repository = DataBaseServices();
  Future<Map<String, double>> getLocationCollectionData(List<String> locations) async {
    return await _repository.calculateCollectionForLocations(locations);
  }
  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
    //fetchData();
  }

  // List<String> locations = ['Peshawar','Mardan','Lahore'];
  //
  // Future<void> fetchData() async {
  //
  //
  //   try {
  //     locations.clear();
  //     final data = await DataBaseServices().getLocationData();
  //     locations.addAll(location_assign);
  //     print('${locations.length}');
  //     update();
  //   } catch (e) {
  //     print('Error fetching data: $e');
  //   }
  // }
  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}