/// Generated by Flutter GetX Starter on 2023-11-05 07:21
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../widgets/appBar.dart';
import '../create_report/logic.dart';
import 'location_collection_logic.dart';

final createReportLogic = Get.put(CreateReportLogic());

class LocationCollectionView extends StatelessWidget {
  LocationCollectionView(this.location, {super.key});
  final List<String> location;
  final location_collectionLogic logic = Get.put(location_collectionLogic());

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: appBarWidget(text: 'Location Collection Report'),
        body: FutureBuilder<Map<String, double>>(
          future: logic.getLocationCollectionData(location),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            } else if (snapshot.hasError) {
              return Center(child: Text('Error: ${snapshot.error}'));
            } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
              return const Center(child: Text('No data available.'));
            } else {
              // Data is available, display it using a ListView.builder
              Map<String, double>? locationCollectionData = snapshot.data;
              return ListView.builder(
                itemCount: locationCollectionData?.length,
                itemBuilder: (context, index) {
                  String location = locationCollectionData!.keys.elementAt(index);
                  double totalCollection = locationCollectionData.values.elementAt(index);
                  return ListTile(
                    title: Text('Location name:   $location'),
                    subtitle: Text('Total Collection: ${totalCollection.toStringAsFixed(2)} AED'),
                  );
                },
              );
            }
          },
        ),
      ),
    );
  }
}
