// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lkKHJ8Fg4ba7i96B2TCtB7GUc4TMx8U',
    appId: '1:565137942005:web:6d82baf4fedd5e7e4bacbc',
    messagingSenderId: '565137942005',
    projectId: 'speedpark-c468b',
    authDomain: 'speedpark-c468b.firebaseapp.com',
    storageBucket: 'speedpark-c468b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPCokljBxjgPjK7EAkD_3jUGM-QoKfQI',
    appId: '1:565137942005:android:778d3ac459b355ec4bacbc',
    messagingSenderId: '565137942005',
    projectId: 'speedpark-c468b',
    storageBucket: 'speedpark-c468b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2YaWrgUL1pIqLFPdkowpoNGm6r1gAD8',
    appId: '1:565137942005:ios:50dee2daf78ca4f24bacbc',
    messagingSenderId: '565137942005',
    projectId: 'speedpark-c468b',
    storageBucket: 'speedpark-c468b.appspot.com',
    iosClientId: '565137942005-tgvth74h4mkrvkol51c4mmbt5se4b8vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedParkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2YaWrgUL1pIqLFPdkowpoNGm6r1gAD8',
    appId: '1:565137942005:ios:5e86b1999db4d1d44bacbc',
    messagingSenderId: '565137942005',
    projectId: 'speedpark-c468b',
    storageBucket: 'speedpark-c468b.appspot.com',
    iosBundleId: 'com.example.speedParkApp.RunnerTests',
  );
}
