/// Generated by Flutter GetX Starter on 2023-11-20 16:18
import 'package:get/get.dart';

import '../../../core/model/history/car_history_model.dart';
import '../../../core/services/database.dart';
import 'car_details_from_history_state.dart';

class car_details_from_historyLogic extends GetxController {
  final state = car_details_from_historyState();
  final Rx<List<CarHistoryModel>> _car = Rx<List<CarHistoryModel>>([]);
  List<CarHistoryModel> get car => _car.value;
  final DataBaseServices _repository = DataBaseServices();
  var totalRiyal = 0.0.obs;
  @override
  void onInit() {
    super.onInit();
    _car.bindStream(_repository.getCarHistoryForSuperuser());
    ever(_car, (_) {
      updateTotalRiyal();
    });
  }
  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }
  void updateTotalRiyal() {
    double total = 0.0;
    double totalpakvalue = 0.0;

    for (var record in car) {
      double? riyalValue = double.tryParse(record.amountIncludeTax.toString());
      if (riyalValue != null) {
        total += riyalValue;
      }
    }

    totalRiyal.value = total;



    print('new     Average is is is : $totalRiyal');
    update();
  }


  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}