/// Generated by Flutter GetX Starter on 2023-11-20 16:18
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';

import '../../../core/constants/colors.dart';
import '../../../core/constants/styles.dart';
import '../../../core/model/history/car_history_model.dart';
import '../../../widgets/appBar.dart';
import '../../../widgets/mytext.dart';
import 'car_details_from_history_logic.dart';
import 'car_details_from_history_state.dart';

class car_details_from_historyView extends StatelessWidget {
  final car_details_from_historyLogic logic = Get.put(car_details_from_historyLogic());
  final car_details_from_historyState state = Get.find<car_details_from_historyLogic>().state;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar:  appBarWidget(text: 'Car Record Report'),
        body:Obx(() {
          return logic.car.isEmpty
              ? Center(
            child: Text(
              'Sorry Car Details not available',
              style: normalTextStyle,
            ),
          )
              : Container(
            margin: EdgeInsets.symmetric(horizontal: 15, vertical: 15),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(height: 20.h),
                Expanded(
                    child: ListView.builder(
                      itemCount: logic.car.length,
                      itemBuilder: (context, index) {
                        return CarDetails(
                          carInfo: logic.car[index],
                        );
                      },
                    )),
              ],
            ),
          );
        }),
         bottomNavigationBar: Container(
          padding: EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.5),
            spreadRadius: 5,
            blurRadius: 7,
            offset: Offset(0, 3),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Row(
            children: [
              Text('Total Amount: ${NumberFormat('#,##,###').format(logic.totalRiyal.value)} AED',style: TextStyle(fontWeight: FontWeight.bold,fontSize: 20),),


            ],
          ),

        ],
      ),
    ),

      ),


    );
  }
}
class CarDetails extends StatelessWidget {
  final CarHistoryModel carInfo;

  CarDetails({required this.carInfo});
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: kPrimary,
        borderRadius: BorderRadius.circular(15),
        boxShadow: [
          BoxShadow(
            color: kPrimary.withOpacity(0.4),
            blurRadius: 10,
          ),

        ],

      ),
      margin:const  EdgeInsets.symmetric(vertical: 10, horizontal: 15),
      child: Padding(
        padding: const EdgeInsets.all(15),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            MyText(
              text: 'Plate No: ${carInfo.platNumber}',
              size: 14.sp,
              color: white,
            ),
            const SizedBox(height: 5),
            MyText(
              text: 'Parking Location: ${carInfo.userLocation}',
              size: 14.sp,
              color: white,
            ),
            const SizedBox(height: 5),
            MyText(
              text: 'Registered: ${carInfo.registerDate} ${carInfo.registerTime}',
              size: 14.sp,
              color: white,
            ),
            const SizedBox(height: 5),
            MyText(
              text: 'Delivered: ${carInfo.deliveredDate} ${carInfo.deliveredTime}',
              size: 14.sp,
              color: white,
            ),
            const SizedBox(height: 5),
            MyText(
              text: 'Location Type: ${carInfo.locationTypeCheck=='Paid'?carInfo.locationTypeCheck:'Normal'}',
              size: 14.sp,
              color: white,
            ),
            Visibility(
              visible: carInfo.locationTypeCheck == 'Paid',
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const SizedBox(height: 5),
                  MyText(
                    text: 'Select Charges: ${carInfo.selectCharges}',
                    size: 14.sp,
                    color: white,
                  ),
                  // SizedBox(height: 5),
                  // MyText(
                  //   text: 'Amount: ${carInfo.amount_include_tax} AED',
                  //   size: 14.sp,
                  //   color: kwhite,
                  // ),
                  // SizedBox(height: 5),
                  // carInfo.select_charges == 'Per hour'
                  //     ? MyText(
                  //   text: 'Additional Hour Charges: ${carInfo.perhour} AED',
                  //   size: 14.sp,
                  //   color: kwhite,
                  // )
                  //     : Container(),
                  // SizedBox(height: 5),
                  // carInfo.taxCharge != 'Tax Inclusive'
                  //     ? MyText(
                  //   text: 'Tax: 5%',
                  //   size: 14.sp,
                  //   color: kwhite,
                  // )
                  //     : MyText(
                  //   text: 'Tax: Tax Exclusive',
                  //   size: 14.sp,
                  //   color: kwhite,
                  // ),
                  const SizedBox(height: 5),
                  MyText(
                    text: 'Total Charges: ${carInfo.amountIncludeTax} AED',
                    size: 14.sp,
                    color: white,
                  ),
                ],
              ),
            )


          ],
        ),
      ),
    );
  }
}
