/// Generated by Flutter GetX Starter on 2023-11-20 17:58
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

import '../../../core/services/database.dart';
import 'driver_name_details_state.dart';

class driver_name_detailsLogic extends GetxController {
  final state = driver_name_detailsState();
  final TextEditingController driveNameController = TextEditingController();
  final DataBaseServices _repository = DataBaseServices();
  RxString searchResult = ''.obs;
  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    driveNameController.clear();
    super.onClose();
  }
  void searchCar() async {
    final driveName = driveNameController.text.trim().toLowerCase();
    if (driveName.isNotEmpty) {
      final result = await _repository.fetchCarDetails(driveName);
      searchResult.value = result;
    }
    update();
  }
}